name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  get_it: ^5.0.1
  http: ^0.12.2
  equatable: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Bold.ttf
        - asset: fonts/montserrat/Montserrat-Regular.ttf
    - family: Hind
      fonts:
        - asset: fonts/hind/Hind-Regular.ttf
